1).Write a function so that the columns of the output matrix are powers of the input
vector.

In [16]:
import numpy as np
def vander():
    arr = []
    m = c-1
    for i in IP_matrix:
        if increasing.upper()=='T':
            for j in range(0,m+1):
                arr.append(i**j)
        elif increasing.upper()=='F':
            for j in range(m,-1,-1):
                arr.append(i**j)
    if len(arr)>0:
        print('\nThe output matrix is: \n'+'-'*20+'\n{}'.format(np.array(arr).reshape(-1,c)))
    else:
        print('\nSomething wrong with your entry !!!!')

In [18]:
IP_matrix = [1,2,3,5]
c = 4
increasing = input('True or False?\n(T/F)  ')

vander()

True or False?
(T/F)  t

The output matrix is: 
--------------------
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


2).Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
def mov_avg_val(l,w):
    mov_avg = []
    for i in range(len(l)-2):
        mov_avg.append(round((l[i]+l[i+1]+l[i+2])/w,1))
    print('\nThe moving average is = {}'.format(mov_avg))
    print('The lenght of the list L-N+1 = \"%d\"'%len(mov_avg))

In [4]:
l = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
w = 3

mov_avg_val(l,w)


The moving average is = [5.0, 4.7, 5.7, 6.7, 9.7, 28.7, 49.3, 72.7, 84.0, 93.3, 116.3]
The lenght of the list L-N+1 = "11"
